# CMake toolchain file for AROS x86_64 (uses ../AROS/toolchain + ../AROS/sdk)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(AROS_ROOT "/Volumes/arosmain")
set(CMAKE_C_COMPILER   ${AROS_ROOT}/toolchain-mainline/x86_64-aros-gcc)
set(CMAKE_CXX_COMPILER ${AROS_ROOT}/toolchain-mainline/x86_64-aros-g++)
set(CMAKE_AR           ${AROS_ROOT}/toolchain-mainline/x86_64-aros-ar)
set(CMAKE_RANLIB       ${AROS_ROOT}/toolchain-mainline/x86_64-aros-ranlib)
set(CMAKE_SYSROOT      ${AROS_ROOT}/build/bin/pc-x86_64/AROS/Developer)
set(CMAKE_FIND_ROOT_PATH ${AROS_ROOT}/build/bin/pc-x86_64/AROS/Developer ${CMAKE_CURRENT_LIST_DIR}/deps/prefix)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_C_FLAGS_INIT   "-I${AROS_ROOT}/build/bin/pc-x86_64/AROS/Developer/include")
set(CMAKE_CXX_FLAGS_INIT "-I${AROS_ROOT}/build/bin/pc-x86_64/AROS/Developer/include")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-L${AROS_ROOT}/build/bin/pc-x86_64/AROS/Developer/lib")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE OFF)
set(CMAKE_CXX_COMPILE_OPTIONS_PIC "")
set(CMAKE_C_COMPILE_OPTIONS_PIC "")
set(AROS ON)
