#!/usr/bin/env python3
"""Compile contrib's SDL3-aros-staticlib file list with the ABIv11 toolchain."""
import argparse, re, subprocess, sys, datetime
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor

ap = argparse.ArgumentParser()
ap.add_argument('--deps', required=True)
ap.add_argument('--toolchain', required=True)
ap.add_argument('--sdk', required=True)
ap.add_argument('--build', required=True)
a = ap.parse_args()

deps, prefix = Path(a.deps), Path(a.deps)
src = deps / 'src/SDL3-3.4.12'
cc = Path(a.toolchain) / 'x86_64-aros-gcc'
ar = Path(a.toolchain) / 'x86_64-aros-ar'
sdk = Path(a.sdk)

# FILES := \ ... one $(ARCHSRCDIR)/path per line, no extension.
mm = (deps / 'src/contrib-sdl3/mmakefile.src').read_text()
# FILES is assembled from one ":=" and several "+=" blocks, each a
# backslash-continued list. The test-suite lists further down use their own
# variables, so stop at the end of every continuation rather than grepping
# the whole file.
block = []
lines = mm.splitlines()
for i, ln in enumerate(lines):
    if re.match(r'FILES\s*[:+]?=', ln):
        for cont in lines[i:]:
            block.append(cont)
            if not cont.rstrip().endswith('\\'):
                break
files = re.findall(r'\$\(ARCHSRCDIR\)/(\S+)', '\n'.join(block))
assert len(files) > 150, f'only {len(files)} files parsed from mmakefile.src'

objdir = Path(a.build) / 'sdl3'
objdir.mkdir(parents=True, exist_ok=True)
adate = datetime.date.today().strftime('%d.%m.%Y')

INCLUDES = [f'-I{src}/include', f'-I{src}/include/build_config',
            f'-I{src}', f'-I{src}/src', f'-I{sdk}/include']
# Mainline AROS keeps libiconv apart from the SDK's own headers and libraries,
# under SDK/Extras; ABIv11 has both in include/ and lib/. Use the directories
# where they exist rather than branching on the ABI name.
extras_inc = sdk / 'SDK/Extras/include'
extras_lib = sdk / 'SDK/Extras/lib'
if extras_inc.is_dir():
    INCLUDES.append(f'-I{extras_inc}')
CFLAGS = ['-std=gnu99', '-O2', '-DSDL3_AROS_STATIC', f'-DADATE="{adate}"',
          '-Wno-stringop-truncation', '-w']

units = [(src / (f + '.c'), objdir / (f.replace('/', '_') + '.o')) for f in files]
units.append((deps / 'src/contrib-sdl3/SDL3_static.c', objdir / 'SDL3_static.o'))


def build(u):
    s, o = u
    if not s.exists():
        return s, 127, f'missing source {s}'
    r = subprocess.run([str(cc), f'--sysroot={sdk}'] + CFLAGS + INCLUDES +
                       ['-c', str(s), '-o', str(o)], capture_output=True, text=True)
    return s, r.returncode, r.stdout + r.stderr


fail = 0
with ThreadPoolExecutor(max_workers=8) as ex:
    for s, rc, out in ex.map(build, units):
        if rc != 0:
            fail += 1
            print(f'FAIL {s.name}\n{out[:600]}', file=sys.stderr)

print(f'compiled {len(units) - fail}/{len(units)} objects')
if fail:
    sys.exit(1)

(prefix / 'lib').mkdir(parents=True, exist_ok=True)
lib = prefix / 'lib/libSDL3_static.a'
lib.unlink(missing_ok=True)
objs = [str(o) for _, o in units]
for i in range(0, len(objs), 100):
    subprocess.run([str(ar), 'rcs', str(lib)] + objs[i:i + 100], check=True)

incdst = prefix / 'include/SDL3'
incdst.mkdir(parents=True, exist_ok=True)
for h in (src / 'include/SDL3').glob('*.h'):
    (incdst / h.name).write_bytes(h.read_bytes())

# find_package(SDL3 REQUIRED CONFIG) needs a package config; contrib's build
# would install one, ours has to write it. Static, so the consumer must also
# get the libraries SDL3 itself pulls in — GL for the AROS OpenGL backend,
# iconv for SDL_iconv, pthread/m for the rest.
cfgdir = prefix / 'lib/cmake/SDL3'
cfgdir.mkdir(parents=True, exist_ok=True)
(cfgdir / 'SDL3Config.cmake').write_text(f"""# Generated by scripts/build-sdl3.py - do not edit.
# Points at the static SDL3 built from contrib's SDL3-aros-staticlib file list.
if(NOT TARGET SDL3::SDL3)
    add_library(SDL3::SDL3 STATIC IMPORTED)
    set_target_properties(SDL3::SDL3 PROPERTIES
        IMPORTED_LOCATION "{lib}"
        INTERFACE_INCLUDE_DIRECTORIES "{prefix / 'include'}"
        INTERFACE_LINK_LIBRARIES "GL;iconv;pthread;m"{f'''
        INTERFACE_LINK_DIRECTORIES "{extras_lib}"''' if extras_lib.is_dir() else ''})
endif()
# OpenLoco links SDL3::SDL3; these aliases exist because upstream projects vary.
if(NOT TARGET SDL3::SDL3-static)
    add_library(SDL3::SDL3-static ALIAS SDL3::SDL3)
endif()
if(NOT TARGET SDL3::Headers)
    add_library(SDL3::Headers ALIAS SDL3::SDL3)
endif()
set(SDL3_FOUND TRUE)
""")
(cfgdir / 'SDL3ConfigVersion.cmake').write_text("""set(PACKAGE_VERSION "3.4.12")
if(PACKAGE_FIND_VERSION VERSION_GREATER PACKAGE_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    set(PACKAGE_VERSION_EXACT TRUE)
endif()
""")

print(f'{lib} ({lib.stat().st_size // 1024} KiB)')
print(f'headers in {incdst}')
print(f'cmake package in {cfgdir}')
