#!/usr/bin/env python3
"""Build openal-soft as a static library for an AROS ABI whose SDK has none.

Mainline AROS has neither libopenal.a nor LIBS:openal.library (see
scripts/fetch-deps.sh). This compiles the same sources contrib compiles for its
own libopenal.static.a - contrib/MultiMedia/libs/OpenAL/mmakefile.src, version
1.19.1 - with contrib's config.h and the AHI backend its AROS diff adds, and
writes the result to <deps>/lib/libopenal.static.a.

The file list is written out here rather than parsed from mmakefile.src: that
file selects files through nested version comparisons (1.16 / 1.18 / 1.19),
and parsing make conditionals is the fragile part. The list below is what
those conditionals resolve to for 1.19.1 on x86_64.
"""
import argparse, subprocess, sys
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor

ap = argparse.ArgumentParser()
ap.add_argument('--deps', required=True)
ap.add_argument('--toolchain', required=True)
ap.add_argument('--sdk', required=True)
ap.add_argument('--build', required=True)
a = ap.parse_args()

VER = '1.19.1'
deps = Path(a.deps)
src = deps / f'src/openal-soft-{VER}'
contrib = deps / 'src/contrib-openal'
cc = Path(a.toolchain) / 'x86_64-aros-gcc'
ar = Path(a.toolchain) / 'x86_64-aros-ar'
sdk = Path(a.sdk)
gen = Path(a.build) / 'openal-gen'
objdir = Path(a.build) / 'openal'
gen.mkdir(parents=True, exist_ok=True)
objdir.mkdir(parents=True, exist_ok=True)

if not src.is_dir():
    sys.exit(f'{src} missing - run scripts/fetch-deps.sh first')

# --- generated files, as contrib's mmakefile makes them ----------------------
# version.h: sed over version.h.in.
vin = (src / 'version.h.in').read_text()
(gen / 'version.h').write_text(vin.replace('${LIB_VERSION}', VER)
                                  .replace('${GIT_BRANCH}', 'UNKNOWN')
                                  .replace('${GIT_COMMIT_HASH}', 'unknown'))
# ef_null.c: a copy of Alc/effects/null.c under a name that does not collide
# with Alc/backends/null.c in a flat object directory.
(gen / 'ef_null.c').write_bytes((src / 'Alc/effects/null.c').read_bytes())
# bsinc_inc.h: generated by a host tool, bsincgen, built with the host's cc.
host_tool = gen / 'bsincgen'
subprocess.run(['cc', '-O2', '-o', str(host_tool),
                str(src / 'native-tools/bsincgen.c'), '-lm'], check=True)
subprocess.run([str(host_tool), str(gen / 'bsinc_inc.h')], check=True)

# --- the 1.19.1 file list from mmakefile.src ---------------------------------
OPENAL32 = ['alAuxEffectSlot', 'alBuffer', 'alEffect', 'alError', 'alExtension',
            'alFilter', 'alListener', 'alSource', 'alState', 'sample_cvt', 'event']
COMMON = ['alcomplex', 'almalloc', 'atomic', 'threads', 'rwlock', 'uintmap']
ALC = ['ALc', 'ALu', 'bs2b', 'helpers', 'hrtf', 'panning',
       'mixer/mixer_c', 'mixer/mixer_sse', 'mixer/mixer_sse2', 'mixer/mixer_sse3',
       'alconfig', 'converter', 'mastering', 'ringbuffer', 'uhjfilter',
       'ambdec', 'bformatdec', 'mixvoice']
BACKENDS = ['ahi', 'base', 'null', 'loopback', 'wave']
EFFECTS = ['autowah', 'chorus', 'compressor', 'dedicated', 'distortion', 'echo',
           'equalizer', 'modulator', 'reverb', 'fshifter', 'pshifter']
FILTERS = ['filter', 'nfc', 'splitter']

files = ([src / 'OpenAL32' / f for f in OPENAL32] +
         [src / 'common' / f for f in COMMON] +
         [src / 'Alc' / f for f in ALC] +
         [src / 'Alc/backends' / f for f in BACKENDS] +
         [src / 'Alc/effects' / f for f in EFFECTS] +
         [src / 'Alc/filters' / f for f in FILTERS] +
         [gen / 'ef_null'])
units = []
for f in files:
    rel = f.relative_to(src) if f.is_relative_to(src) else Path('gen') / f.name
    units.append((f.with_suffix('.c'), objdir / (str(rel).replace('/', '_') + '.o')))

INCLUDES = [f'-I{gen}', f'-I{contrib}', f'-I{src}', '-iquote', f'{src}/include',
            f'-I{src}/OpenAL32/Include', f'-I{src}/Alc', f'-I{src}/common',
            f'-I{sdk}/include']
CFLAGS = ['-std=gnu99', '-O2', '-ffast-math', '-Wall', '-w',
          '-DAL_ALEXT_PROTOTYPES', '-D_GNU_SOURCE=1', '-msse', '-mfpmath=sse']


def build(u):
    s, o = u
    if not s.exists():
        return s, 127, f'missing source {s}'
    r = subprocess.run([str(cc), f'--sysroot={sdk}'] + CFLAGS + INCLUDES +
                       ['-c', str(s), '-o', str(o)], capture_output=True, text=True)
    return s, r.returncode, r.stdout + r.stderr


fail = 0
with ThreadPoolExecutor(max_workers=8) as ex:
    for s, rc, out in ex.map(build, units):
        if rc != 0:
            fail += 1
            print(f'FAIL {s}\n{out[:800]}', file=sys.stderr)
print(f'compiled {len(units) - fail}/{len(units)} objects')
if fail:
    sys.exit(1)

lib = deps / 'lib/libopenal.static.a'
lib.parent.mkdir(parents=True, exist_ok=True)
lib.unlink(missing_ok=True)
subprocess.run([str(ar), 'rcs', str(lib)] + [str(o) for _, o in units], check=True)
print(f'{lib} ({lib.stat().st_size // 1024} KiB)')
