#!/bin/sh
# Write CMake package config files for SDK libraries that ship none.
#
#   scripts/make-cmake-packages.sh [abi]      default abi: abiv11
#
# OpenLoco does find_package(OpenAL CONFIG) and falls back to pkg-config; the
# AROS SDK has libopenal.a and the AL/ headers but neither a config package nor
# a .pc file, so both paths fail. This writes the config package rather than
# patching upstream's CMake, so the game's build files stay untouched.
set -e
. "$(dirname "$0")/env.sh"

ABI=${1:-abiv11}
SDK=$(abi_sdk "$ABI")
DEPS=$(abi_deps "$ABI")

# Two cases, told apart by what exists rather than by the ABI's name:
#   - the SDK has libopenal.a (ABIv11): link stubs into the shared
#     openal.library 1.16.0 that AROS One installs;
#   - it does not (mainline): our static build of openal-soft 1.19.1 from
#     scripts/build-openal.sh, linked into the game. No openal.library needed.
if [ -f "$SDK/lib/libopenal.a" ]; then
    OPENAL_LIB=$SDK/lib/libopenal.a
    OPENAL_NOTE="libopenal.a is link stubs into the shared openal.library (openal-soft 1.16.0 on AROS One), not a static library."
    OPENAL_DEPS=""
elif [ -f "$DEPS/lib/libopenal.static.a" ]; then
    OPENAL_LIB=$DEPS/lib/libopenal.static.a
    OPENAL_NOTE="static openal-soft 1.19.1 built by scripts/build-openal.sh - this SDK has no libopenal.a and the system no openal.library."
    OPENAL_DEPS="pthread;m"
else
    echo "no libopenal.a in $SDK/lib and no static build in $DEPS/lib - run scripts/build-openal.sh $ABI" >&2
    exit 1
fi

DIR=$DEPS/lib/cmake/OpenAL
mkdir -p "$DIR"
cat > "$DIR/OpenALConfig.cmake" <<CFG
# Generated by scripts/make-cmake-packages.sh - do not edit.
# $OPENAL_NOTE
if(NOT TARGET OpenAL::OpenAL)
    add_library(OpenAL::OpenAL STATIC IMPORTED)
    set_target_properties(OpenAL::OpenAL PROPERTIES
        IMPORTED_LOCATION "$OPENAL_LIB"
        INTERFACE_INCLUDE_DIRECTORIES "$SDK/include"
        INTERFACE_LINK_LIBRARIES "$OPENAL_DEPS")
endif()
set(OPENAL_INCLUDE_DIR "$SDK/include")
set(OPENAL_LIBRARY "$OPENAL_LIB")
set(OpenAL_FOUND TRUE)
CFG
cat > "$DIR/OpenALConfigVersion.cmake" <<'CFG'
set(PACKAGE_VERSION "1.19.1")
set(PACKAGE_VERSION_COMPATIBLE TRUE)
set(PACKAGE_VERSION_EXACT TRUE)
CFG

echo "wrote $DIR/OpenALConfig.cmake"
