#!/bin/sh
# Write CMake package config files for SDK libraries that ship none.
#
#   scripts/make-cmake-packages.sh [abi]      default abi: abiv11
#
# OpenLoco does find_package(OpenAL CONFIG) and falls back to pkg-config; the
# AROS SDK has libopenal.a and the AL/ headers but neither a config package nor
# a .pc file, so both paths fail. This writes the config package rather than
# patching upstream's CMake, so the game's build files stay untouched.
set -e
. "$(dirname "$0")/env.sh"

ABI=${1:-abiv11}
SDK=$(abi_sdk "$ABI")
DEPS=$(abi_deps "$ABI")

[ -f "$SDK/lib/libopenal.a" ] || { echo "no libopenal.a in $SDK/lib" >&2; exit 1; }

DIR=$DEPS/lib/cmake/OpenAL
mkdir -p "$DIR"
cat > "$DIR/OpenALConfig.cmake" <<CFG
# Generated by scripts/make-cmake-packages.sh - do not edit.
# The AROS SDK's OpenAL (openal-soft 1.19.1) has no config package of its own.
if(NOT TARGET OpenAL::OpenAL)
    add_library(OpenAL::OpenAL STATIC IMPORTED)
    set_target_properties(OpenAL::OpenAL PROPERTIES
        IMPORTED_LOCATION "$SDK/lib/libopenal.a"
        INTERFACE_INCLUDE_DIRECTORIES "$SDK/include")
endif()
set(OPENAL_INCLUDE_DIR "$SDK/include")
set(OPENAL_LIBRARY "$SDK/lib/libopenal.a")
set(OpenAL_FOUND TRUE)
CFG
cat > "$DIR/OpenALConfigVersion.cmake" <<'CFG'
set(PACKAGE_VERSION "1.19.1")
set(PACKAGE_VERSION_COMPATIBLE TRUE)
set(PACKAGE_VERSION_EXACT TRUE)
CFG

echo "wrote $DIR/OpenALConfig.cmake"
